## CARGAR LOS DATOS

Importamos las librerias numpy (operaciones matemáticas), pandas (dataframes), seaborn y matplotlib(visualización).

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

Leemos el archivo .csv original y creamos una copia.

In [2]:
dataset = pd.read_csv("../data/GBvideos_cc50_202101.csv")
datasetcopia = dataset

## INSPECCIONAR LOS DATOS

Exploramos el dataframe, con la instrucción *info()*

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38916 entries, 0 to 38915
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                38916 non-null  object
 1   trending_date           38916 non-null  object
 2   title                   38916 non-null  object
 3   channel_title           38916 non-null  object
 4   category_id             38916 non-null  int64
 5   publish_time            38916 non-null  object
 6   tags                    38916 non-null  object
 7   views                   38916 non-null  int64
 8   likes                   38916 non-null  int64
 9   dislikes                38916 non-null  int64
 10  comment_count           38916 non-null  int64
 11  thumbnail_link          38916 non-null  object
 12  comments_disabled       38916 non-null  bool
 13  ratings_disabled        38916 non-null  bool
 14  video_error_or_removed  38916 non-null  bool
 15  description             38304 non-null  object
 16  state                   38916 non-null  object
 17  lat                     38916 non-null  float64
 18  lon                     38916 non-null  float64
 19  geometry                38916 non-null  object
dtypes: bool(3), float64(2), int64(5), object(10)
memory usage: 3.7+ MB

Dado esta salida, sabemos que existen 38916 entradas (filas), con 19 variables (columnas)

Además. inspeccionamos con la función *describe()*

In [6]:
dataset.describe()

,category_id,views,likes,dislikes,comment_count,lat,lon
count,38916.000000,3.891600e+04,3.891600e+04,3.891600e+04,3.891600e+04,38916.000000,38916.000000
mean,16.827937,5.911944e+06,1.345196e+05,7.612560e+03,1.308835e+04,53.383720,-2.379078
std,7.752728,1.900121e+07,3.499893e+05,5.095683e+04,5.066740e+04,2.043531,2.103878
min,1.000000,8.510000e+02,0.000000e+00,0.000000e+00,0.000000e+00,50.133722,-7.333284
25%,10.000000,2.515272e+05,5.897000e+03,2.000000e+02,6.790000e+02,51.499995,-3.529950
50%,20.000000,9.818890e+05,2.518250e+04,8.210000e+02,2.478000e+03,53.200020,-2.180007
75%,24.000000,3.683628e+06,1.140892e+05,3.357500e+03,9.241500e+03,54.879995,-1.080022
max,43.000000,4.245389e+08,5.613827e+06,1.944971e+06,1.626501e+06,58.966981,1.300013

Ahora, veamos las entradas con la instrucción *head()*

In [7]:
dataset.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,state,lat,lon,geometry
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,Devon,50.700405,-3.529950,POINT (-3.529950197 50.70040529)
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...,Manchester,53.500415,-2.247987,POINT (-2.247987103 53.50041526)
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,Bath And North East Somerset,51.383749,-2.350022,POINT (-2.350022218 51.3837486)
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...,Aberdeen,57.170398,-2.079987,POINT (-2.079987021 57.17039797)
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...,Southampton,50.900031,-1.399977,POINT (-1.399976849 50.90003135)

## PRE-PROCESAR LOS DATOS

### VALORES FALTANTES

Vamos a inspeccionar cuantos NAs existen en cada columna

In [8]:
datasetcopia.isna().sum()

video_id                    0
trending_date               0
title                       0
channel_title               0
category_id                 0
publish_time                0
tags                        0
views                       0
likes                       0
dislikes                    0
comment_count               0
thumbnail_link              0
comments_disabled           0
ratings_disabled            0
video_error_or_removed      0
description               612
state                       0
lat                         0
lon                         0
geometry                    0
dtype: int64

Podemos notar que solo, el description tiene 612 valore NAs. Entonces, podemos asignar su valor con 'No description'.

In [9]:
datasetcopia['description'].fillna('No description', inplace=True)

Revisamos la cantidad de NA's para confirmar.

In [11]:
datasetcopia.isna().sum()

video_id                  0
trending_date             0
title                     0
channel_title             0
category_id               0
publish_time              0
tags                      0
views                     0
likes                     0
dislikes                  0
comment_count             0
thumbnail_link            0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
description               0
state                     0
lat                       0
lon                       0
geometry                  0
dtype: int64

### OUTLIERS

Creamos una función para arreglar los outliers

In [12]:
def arreglarOutliers(data):
    outliers = data.quantile([0.05,0.95])
    n = len(data)
    outliers = list(outliers)
    mean = data.mean()
    median = data.median()
    
    for element in range(n):
        if int(data[element]) < int(outliers[0]):
            data.loc[element]= mean
        elif int(data[element]) > int(outliers[1]):
            data.loc[element]= median

    return data

Outliers de la columnas 'views'

### TRENDING_DATE, PUBLISH_TIME

In [13]:
datasetcopia['trending_date'] = pd.to_datetime(datasetcopia['trending_date'], format='%y.%d.%m')
datasetcopia['publish_time'] = pd.to_datetime(datasetcopia['publish_time'])

### ARREGLAR OUTLIERS DE LA COLUMNA FECHA

In [14]:
def arreglarOutliersfecha(data):
    outliers = data.quantile([0.02,0.98])
    n = len(data)
    outliers = list(outliers)
    for element in range(n):
        if data[element] > outliers[1] or data[element]<outliers[0]:
            data[element] = np.nan

### CREAR COLUMNA PARA DESCRIPCIÓN DE LA CATEGORIA

In [15]:
dfCategory = pd.read_json('GB_category_id.json')

In [16]:
dfCategory.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [17]:
dfCategory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kind    32 non-null     object
 1   etag    32 non-null     object
 2   items   32 non-null     object
dtypes: object(3)
memory usage: 448.0+ bytes

In [18]:
items = dfCategory['items']

In [19]:
category = dict()
for i in range(len(dfCategory)):
    category[items[i]['id']] = items[i]['snippet']['title']

In [20]:
datasetcopia['category_description'] = [ category[str(i)] for i in datasetcopia['category_id']]
datasetcopia['category_description']

0          Howto & Style
1          Entertainment
2                  Music
3                 Sports
4        News & Politics
              ...
38911              Music
38912              Music
38913              Music
38914      Entertainment
38915              Music
Name: category_description, Length: 38916, dtype: object

### EXPORT CSV

In [22]:
datasetcopia.to_csv('../data/GB_dataset_preprocessed.csv', index=False)

In [23]:
data = pd.read_csv('../data/GB_dataset_preprocessed.csv')
data

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,state,lat,lon,geometry,category_description
0,Jw1Y-zhQURU,2017-11-14,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10 07:38:29+00:00,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,...,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...,Devon,50.700405,-3.529950,POINT (-3.529950197 50.70040529),Howto & Style
1,3s1rvMFUweQ,2017-11-14,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12 06:24:44+00:00,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,...,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...,Manchester,53.500415,-2.247987,POINT (-2.247987103 53.50041526),Entertainment
2,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,Bath And North East Somerset,51.383749,-2.350022,POINT (-2.350022218 51.3837486),Music
3,PUTEiSjKwJU,2017-11-14,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13 02:30:38+00:00,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,...,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...,Aberdeen,57.170398,-2.079987,POINT (-2.079987021 57.17039797),Sports
4,rHwDegptbI4,2017-11-14,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13 01:45:13+00:00,[none],9815,30,2,...,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...,Southampton,50.900031,-1.399977,POINT (-1.399976849 50.90003135),News & Politics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,2018-06-14,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09 07:00:01+00:00,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,...,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,Plymouth,50.385386,-4.159989,POINT (-4.159989259 50.38538576),Music
38912,IP8k2xkhOdI,2018-06-14,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11 17:09:16+00:00,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,...,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,Omagh,54.600012,-7.300004,POINT (-7.300004315 54.60001223),Music
38913,Il-an3K9pjg,2018-06-14,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08 11:05:08+00:00,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,...,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,Kent,51.133712,1.300013,POINT (1.300013386 51.13371218),Music
38914,-DRsfNObKIQ,2018-06-14,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08 20:32:32+00:00,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,...,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,Glasgow,55.874405,-4.250707,POINT (-4.250707236 55.87440472),Entertainment
38915,4YFo4bdMO8Q,2018-06-14,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11 04:06:35+00:00,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,...,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,Cumbria,54.879995,-2.929987,POINT (-2.929986818 54.87999514),Music

## Nuevo data frame con las frecuencias

In [34]:
data1 = data.set_index(['trending_date', 'video_id'])
data1.head()

                                                                       title  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU      John Lewis Christmas Ad 2017 - #MozTheMonster
              3s1rvMFUweQ          Taylor Swift: …Ready for It? (Live) - SNL
              n1WpP7iowLc         Eminem - Walk On Water (Audio) ft. Beyoncé
              PUTEiSjKwJU  Goals from Salford City vs Class of 92 and Fri...
              rHwDegptbI4  Dashcam captures truck's near miss with child ...

                                        channel_title  category_id  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU                  John Lewis           26
              3s1rvMFUweQ         Saturday Night Live           24
              n1WpP7iowLc                  EminemVEVO           10
              PUTEiSjKwJU  Salford City Football Club           17
              rHwDegptbI4            Cute Girl Videos           25

                                        publish_time  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU  2017-11-10 07:38:29+00:00
              3s1rvMFUweQ  2017-11-12 06:24:44+00:00
              n1WpP7iowLc  2017-11-10 17:00:03+00:00
              PUTEiSjKwJU  2017-11-13 02:30:38+00:00
              rHwDegptbI4  2017-11-13 01:45:13+00:00

                                                                        tags  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU  christmas|"john lewis christmas"|"john lewis"|...
              3s1rvMFUweQ  SNL|"Saturday Night Live"|"SNL Season 43"|"Epi...
              n1WpP7iowLc  Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...
              PUTEiSjKwJU  Salford City FC|"Salford City"|"Salford"|"Clas...
              rHwDegptbI4                                             [none]

                              views   likes  dislikes  comment_count  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU   7224515   55681     10247           9479
              3s1rvMFUweQ   1053632   25561      2294           2757
              n1WpP7iowLc  17158579  787420     43420         125882
              PUTEiSjKwJU     27833     193        12             37
              rHwDegptbI4      9815      30         2             30

                                                           thumbnail_link  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU  https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg
              3s1rvMFUweQ  https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg
              n1WpP7iowLc  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg
              PUTEiSjKwJU  https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg
              rHwDegptbI4  https://i.ytimg.com/vi/rHwDegptbI4/default.jpg

                           comments_disabled  ratings_disabled  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU              False             False
              3s1rvMFUweQ              False             False
              n1WpP7iowLc              False             False
              PUTEiSjKwJU              False             False
              rHwDegptbI4              False             False

                           video_error_or_removed  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU                   False
              3s1rvMFUweQ                   False
              n1WpP7iowLc                   False
              PUTEiSjKwJU                   False
              rHwDegptbI4                   False

                                                                 description  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU  Click here to continue the story and make your...
              3s1rvMFUweQ  Musical guest Taylor Swift performs …Ready for...
              n1WpP7iowLc  Eminem's new track Walk on Water ft. Beyoncé i...
              PUTEiSjKwJU  Salford drew 4-4 against the Class of 92 and F...
              rHwDegptbI4  Dashcam captures truck's near miss with child ...

                                                  state        lat       lon  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU                         Devon  50.700405 -3.529950
              3s1rvMFUweQ                    Manchester  53.500415 -2.247987
              n1WpP7iowLc  Bath And North East Somerset  51.383749 -2.350022
              PUTEiSjKwJU                      Aberdeen  57.170398 -2.079987
              rHwDegptbI4                   Southampton  50.900031 -1.399977

                                                   geometry  \
trending_date video_id
2017-11-14    Jw1Y-zhQURU  POINT (-3.529950197 50.70040529)
              3s1rvMFUweQ  POINT (-2.247987103 53.50041526)
              n1WpP7iowLc   POINT (-2.350022218 51.3837486)
              PUTEiSjKwJU  POINT (-2.079987021 57.17039797)
              rHwDegptbI4  POINT (-1.399976849 50.90003135)

                          category_description
trending_date video_id
2017-11-14    Jw1Y-zhQURU        Howto & Style
              3s1rvMFUweQ        Entertainment
              n1WpP7iowLc                Music
              PUTEiSjKwJU               Sports
              rHwDegptbI4      News & Politics

In [41]:
# Nuevo dataframe con Video Level Stats
video_level = data1.groupby(level=1).last()
video_level['freq'] = data1['title'].groupby(level=1).count()
video_level.sort_values(by=['views'], ascending=False, inplace=True)

video_level.head(10)

,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,state,lat,lon,geometry,category_description,freq
video_id,,,,,,,,,,,,,,,,,,,,
_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,NickyJamTV,10,2018-03-02 05:00:19+00:00,"Bad Bunny|""Amorfoda""|""Dura""|""Daddy Yankee""|""Oz...",424538912,2818771,149275,99380,https://i.ytimg.com/vi/_I_D_8Z4sJE/default.jpg,False,False,False,Disponible en tu plataforma preferida:\nhttps:...,South Ayrshire,55.450400,-4.616680,POINT (-4.61667973 55.4503996),Music,36
9jI-z9QN6g8,"Te Bote Remix - Casper, Nio García, Darell, Ni...",Flow La Movie,10,2018-04-11 22:00:00+00:00,"Te Bote|""Te Bote Remix""|""Flow La Movie""|""Ozuna...",337621571,2581961,166549,113564,https://i.ytimg.com/vi/9jI-z9QN6g8/default.jpg,False,False,False,Flow La Movie Presenta - Te Boté Remix - Caspe...,Tyne And Wear,54.920019,-1.380030,POINT (-1.380029746 54.92001853),Music,33
kLpH1nSLJSs,Bad Bunny - Amorfoda | Video Oficial,Bad Bunny,10,2018-02-15 00:00:03+00:00,"Bad|""Bunny""|""Bad Bunny""|""Video Oficial""|""Music...",328860380,3823879,215530,225216,https://i.ytimg.com/vi/kLpH1nSLJSs/default.jpg,False,False,False,Bad Bunny - Amorfoda | Video Oficial\n\n-Click...,Bristol,51.449998,-2.583315,POINT (-2.583315472 51.44999778),Music,36
wfWkmURBNv8,Ozuna x Romeo Santos - El Farsante Remix,Ozuna,10,2018-01-30 15:00:05+00:00,"Ozuna|""Reggaeton""|""Odisea""|""Odisea The Album""|...",288811992,1618180,151147,67506,https://i.ytimg.com/vi/wfWkmURBNv8/default.jpg,False,False,False,DESCARGA Odisea Aqui: http://apple.co/2vX00sT\...,Westminster,51.499995,-0.116722,POINT (-0.116721844 51.49999473),Music,29
VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07+00:00,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",259721696,5444541,379862,553371,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...,Cardiff,51.499995,-3.225008,POINT (-3.22500757 51.49999473),Music,36
xpVfcZ0ZcFM,Drake - God’s Plan,DrakeVEVO,10,2018-02-17 05:00:01+00:00,"Drake new music|""Drake Gods Plan""|""Drake God’s...",258164991,4737873,117198,301756,https://i.ytimg.com/vi/xpVfcZ0ZcFM/default.jpg,False,False,False,God’s Plan (Official Video)\n\nSong Available ...,Cheshire,53.200020,-2.919987,POINT (-2.919987428 53.20002016),Music,32
ffxKSjUwKdU,Ariana Grande - No Tears Left To Cry,ArianaGrandeVevo,10,2018-04-20 04:00:03+00:00,"Ariana|""Grande""|""No""|""Tears""|""Left""|""To""|""Cry""...",208876887,3394437,150086,259613,https://i.ytimg.com/vi/ffxKSjUwKdU/default.jpg,False,False,False,No Tears Left To Cry (Official Video)Song Avai...,Cornwall,50.133722,-5.550034,POINT (-5.550033611 50.13372154),Music,35
zEf423kYfqk,"Becky G, Natti Natasha - Sin Pijama (Official ...",BeckyGVEVO,10,2018-04-20 10:40:51+00:00,"Becky G|""Natti Natasha""|""Natti Natasha Music""|...",200862743,1668418,142569,97826,https://i.ytimg.com/vi/zEf423kYfqk/default.jpg,False,False,False,Becky G & Natti Natasha – “Sin Pijama”NUEVO SE...,Bath And North East Somerset,51.383749,-2.350022,POINT (-2.350022218 51.3837486),Music,21
FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",169884583,3312868,1753274,845233,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",Manchester,53.500415,-2.247987,POINT (-2.247987103 53.50041526),Entertainment,18
sGIm0-dQd8M,Dura - Daddy Yankee (Video Oficial),Daddy Yankee,10,2018-01-18 22:32:49+00:00,"daddy yankee reggaeton|""daddy yankee youtube""|...",167456025,1633407,74005,65395,https://i.ytimg.com/vi/sGIm0-dQd8M/default.jpg,False,False,False,Dura - Daddy Yankee - nuevo video oficial 2018...,Stockton On Tees,54.580375,-1.230013,POINT (-1.230013063 54.58037518),Music,21

## Preguntas

### 1. ¿Qué categorías de videos son las de mayor tendencia